{% set name = "wcmatch" %}
{% set version = "8.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/wcmatch-{{ version }}.tar.gz
  sha256: 4b2f5758d845d2cb391529f892201916cbb1c2ce10a447c7b7a57a2f4bb5647e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - backrefs >=4.1
    - bracex >=2.0
    - python >=3.5

test:
  imports:
    - wcmatch
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/facelessuser/wcmatch
  summary: Wildcard/glob file name matcher.
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - asford
